Repository Team-Snacks/Snacks-Ninja, pull requests merged in 2022-10, with the labels that each got.

#8 Feature/build 프로젝트 빌드
  frontend/.gitignore
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: 프론트엔드

#11 feat: GridLayout과 구성요소들 생성
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/main.tsx
Labels: 프론트엔드

#15 feat: 그리드 레이아웃 개선
  frontend/src/App.tsx
  frontend/src/WidgetGrid.tsx
Labels: 프론트엔드

#24 fix: 유저 위젯 정보 받아오기 API 에러
  backend/src/main/java/com/example/demo/entity/User.java
  backend/src/main/java/com/example/demo/entity/UserWidget.java
  backend/src/main/java/com/example/demo/entity/UserWidgetId.java
  backend/src/main/java/com/example/demo/entity/Widget.java
  backend/src/main/java/com/example/demo/repository/UserWidgetRepository.java
  backend/src/main/java/com/example/demo/repository/WidgetRepository.java
  backend/src/main/java/com/example/demo/service/DemoService.java
  backend/src/test/java/com/example/demo/DemoApplicationTests.java
Labels: bug, 백엔드

#30 fix: cors 문제
  backend/src/main/java/com/example/demo/SpringConfig.java
Labels: bug, 백엔드

#33 feat: 프론트 백엔드 통합
  frontend/src/App.tsx
  frontend/src/Login.tsx
  frontend/src/atom.ts
  frontend/src/paths.ts
Labels: 프론트엔드

#34 Feature/widget 추가 api 구현
  backend/src/main/java/com/example/demo/controller/DemoController.java
  backend/src/main/java/com/example/demo/dto/WidgetDto.java
  backend/src/main/java/com/example/demo/service/DemoService.java
  backend/src/test/java/com/example/demo/DemoApplicationTests.java
Labels: enhancement, 백엔드

#40 Feature/유저 위젯 정보 서버에 보내기 api 수정
  backend/src/main/java/com/example/demo/service/DemoService.java
Labels: bug, 백엔드

#41 feat/마켓목록,위젯등록 및 추가 구현
  frontend/src/App.tsx
  frontend/src/Market.tsx
Labels: 프론트엔드

#43 feat: market API - widget목록 가져오기, widet 등록
  backend/src/main/java/com/example/demo/controller/MarketController.java
  backend/src/main/java/com/example/demo/controller/UserController.java
  backend/src/main/java/com/example/demo/repository/WidgetRepository.java
  backend/src/main/java/com/example/demo/service/MarketService.java
  backend/src/main/java/com/example/demo/service/UserService.java
  backend/src/test/java/com/example/demo/DemoApplicationTests.java
Labels: 백엔드
